"""Ingredients table

Revision ID: 10795d1edf2d
Revises: e6464aac92a8
Create Date: 2023-10-06 08:51:24.464573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10795d1edf2d'
down_revision = 'e6464aac92a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.String(length=13), nullable=False),
    sa.Column('ingredient_name', sa.String(length=50), nullable=False),
    sa.Column('ingredient_quantity', sa.Integer(), nullable=False),
    sa.Column('ingredient_measurement', sa.Integer(), nullable=False),
    sa.Column('ingredient_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id'),
    sa.UniqueConstraint('ingredient_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    # ### end Alembic commands ###
