"""Users and their roles

Revision ID: 45679af27e8b
Revises: 58d07d888dbd
Create Date: 2023-10-06 13:55:55.392223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45679af27e8b'
down_revision = '58d07d888dbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.String(length=13), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('customer_phone_no', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_mpesa_agent_name', sa.String(length=128), nullable=True))
        batch_op.drop_column('cust_email')
        batch_op.drop_column('cust_name')
        batch_op.drop_column('cust_id')
        batch_op.drop_column('cust_phone_no')
        batch_op.drop_column('cust_mpesa_agent_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cust_mpesa_agent_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('cust_phone_no', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cust_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cust_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('cust_email', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('customer_mpesa_agent_name')
        batch_op.drop_column('customer_phone_no')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    # ### end Alembic commands ###
