"""Redifining some relationships and a new customers table

Revision ID: 58d07d888dbd
Revises: 80dfa08028ed
Create Date: 2023-10-06 10:50:32.130249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58d07d888dbd'
down_revision = '80dfa08028ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_name', sa.String(length=128), nullable=True),
    sa.Column('cust_email', sa.String(length=128), nullable=True),
    sa.Column('cust_phone_no', sa.Integer(), nullable=True),
    sa.Column('cust_mpesa_agent_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('cust_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
