"""Dispatches

Revision ID: 752ee9d365ea
Revises: e23af3bc783c
Create Date: 2023-10-07 12:26:52.536954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752ee9d365ea'
down_revision = 'e23af3bc783c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_date', sa.DateTime(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_details')
    op.drop_table('dispatches')
    # ### end Alembic commands ###
