"""Recipe total cost and recipe_ingredients unit_cost

Revision ID: ad3470c516ae
Revises: 752ee9d365ea
Create Date: 2023-10-09 14:26:34.963803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3470c516ae'
down_revision = '752ee9d365ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
